# Generated by Django 4.2.3 on 2023-07-17 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 17, 2, 32, 58, 8172)),
        ),
    ]
