# Generated by Django 4.2.3 on 2023-07-20 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_description_alter_task_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 20, 10, 55, 14, 106600)),
        ),
    ]
